# mamba env create -f prod.yaml
name: splitter-env
dependencies:
- python>=3.9,<3.10
- numpy<2.0
- librosa
- scipy
- fastapi[standard]
- pip
- IPython
- pydub
- pydantic
- python-dotenv
- httpx

- pip:
  - dora-search
  - einops
  - julius>=0.2.3
  - lameenc>=1.2
  - openunmix
  - pyyaml
  - torch>=1.8.1
  - torchaudio>=0.8,<2.1
  - tqdm
  - essentia
  - pyrubberband