# mamba env create -f prod.yaml
name: splitter-env
channels:
- conda-forge
- defaults
dependencies:
- python>=3.9,<3.10
- numpy<2.0
- librosa
- scipy
- fastapi[standard]
- pip
- IPython
- pydub
- pydantic
- python-dotenv
- httpx
- pytorch-cpu
- torchaudio

- pip:
  - essentia
  - pyyaml
  - tqdm
  - pyrubberband
  - tempocnn