name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Check out code
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - 
      name: Install AWS CLI
      uses: unfor19/install-aws-cli-action@v1
      with:
         version: 2
         verbose: false
         arch: amd64
         rootdir: ""
         workdir: ""
    - 
      name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4.1.0
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        aws-access-key-id: ${{ secrets.ACC_KE }}
        aws-secret-access-key : ${{ secrets.SEC_KE }}

    - name: Docker login with AWS credentials
      run:
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
    - name: Build and push frontend image
      run: |
        docker buildx build \
          --platform linux/amd64 \
          --push \
          --tag ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/tangle/web:latest \
          frontend -f frontend/Dockerfile
    - name: Build and push youtube search api image
      run: |
        docker buildx build \
          --platform linux/amd64 \
          --push \
          --tag ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/tangle/youtube-search:latest \
          api/youtube_search -f api/youtube_search/Dockerfile
    - name: Build and push tangler api image
      run: |
        docker buildx build \
          --platform linux/amd64 \
          --push \
          --tag ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/tangle/tangler:latest \
          api/tangler -f api/tangler/Dockerfile
    
    - name: Force new web deployment
      run: |
        aws ecs update-service \
          --cluster tangle-cluster \
          --service tangleweb \
          --force-new-deployment \
          --region ${{ secrets.AWS_REGION }}
    - name: Force new youtube search deployment
      run: |
        aws ecs update-service \
          --cluster tangle-cluster \
          --service ytsearch \
          --force-new-deployment \
          --region ${{ secrets.AWS_REGION }}
    - name: Force new tangler deployment
      run: |
        aws ecs update-service \
          --cluster tangle-cluster \
          --service tangler \
          --force-new-deployment \
          --region ${{ secrets.AWS_REGION }}
    - name: logout
      run: |
        aws ecr logout --region ${{ secrets.AWS_REGION }} --registry-ids ${{ secrets.AWS_ACCOUNT_ID }}
    - name: Clear Docker cache
      run: |
        docker builder prune --all --force
        docker system prune --all --force
        docker volume prune --force
        docker network prune --force
    - name: Logout from AWS
      run: |
        aws ecr logout --region ${{ secrets.AWS_REGION }} --registry-ids ${{ secrets.AWS_ACCOUNT_ID }}
    - name: Logout from Docker
      run: |
        docker logout
    